# HeavenActivity configuration
# --------------------------------------------------------------------
# Sequences are by default one minute long and 15 of them get stored.
# For more options and explanation visit:
# https://github.com/kaipr/HeavenActivity/wiki
general:
    # Multiplier for all points, if you want more activity for all activities, rise this
    point_multiplier: 1.0
    # Income is given every X sequences (at default, 1 sequence = 1 minute)
    income_sequence: 15
    # Players get notified about their activity every X sequences
    notification_sequence: 6
income:
    # Income enabled?
    enabled: true
    # Minimum activity to get income
    min_activity: 1
    # Allow negative income?
    allow_negative: true
    # Expression to calculate the income players get, available variables:
    # - player_activity: Current activity of player
    # - player_balance: Current money balance of player
    expression: "8 + (((player_activity - 50) / 75) * 8)"